# Generated by Django 4.0.4 on 2022-04-20 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('role', models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Intern', 'Intern')], max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('task_description', models.CharField(max_length=1000, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('attendence_status', models.BooleanField(default=False, null=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
