# Generated by Django 4.0.4 on 2022-04-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='user_profile',
        ),
    ]
