# Generated by Django 4.0.4 on 2022-04-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_attendence_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_profile',
        ),
    ]
