# Generated by Django 4.0.4 on 2022-04-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_profile',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_profile',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
