# Generated by Django 4.0.4 on 2022-04-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_username_task_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
